apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: import-cc-template
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: generate-file-list
            template: generate-file-list-template
        - - name: scan-web
            template: scan-web-template
            arguments:
              artifacts:
                - name: file-list
                  from: '{{steps.generate-file-list.outputs.artifacts.file-list}}'
              parameters:
                - name: batch-definition
                  value: '{{item}}'
            withParam: '{{steps.generate-file-list.outputs.result}}'

    - name: generate-file-list-template
      container:
        image: 10.104.84.38:5000/scanweb:latest
        command: ['/bin/sh', '-c']
        args:
          [
            'sw prepare import commoncrawl -d latest -o batches.json --splitListEvery 10000',
          ]
      outputs:
        artifacts:
          - name: file-list
            path: /app/batches.json

    - name: scan-web-template
      inputs:
        parameters:
          - name: batch-definition
        artifacts:
          - name: file-list
            path: /app/batches.json
      container:
        image: 10.104.84.38:5000/scanweb:latest
        command: [sh, -c]
        args:
          [
            "sw import commoncrawl --fromBatchFile /app/batches.json --batchId $(echo '{{inputs.parameters.batch-definition}}' | jq -r '.batchId') -s postgresql://scanweb:scanweb_password@scanweb-postgres.scanweb.svc.cluster.local:5433/scanweb",
          ]
