apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: import-cc-to-file-template
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: clone-and-build
            template: clone-and-build-template
        - - name: import-domains
            template: import-domains-template
            arguments:
              artifacts:
                - name: build-artifacts
                  from: '{{steps.clone-and-build.outputs.artifacts.build-artifacts}}'

    - name: clone-and-build-template
      container:
        image: node:latest
        command: ['/bin/sh', '-c']
        args:
          [
            'git clone --depth 1 https://github.com/kamiljano/scan-web.git && cd scan-web && npm install && npm run build && tar czf /tmp/build-artifacts.tar.gz .',
          ]
      outputs:
        artifacts:
          - name: build-artifacts
            path: /tmp/build-artifacts.tar.gz

    - name: import-domains-template
      inputs:
        artifacts:
          - name: build-artifacts
            path: /mnt/build-artifacts.tar.gz
      container:
        image: node:latest
        command: ['/bin/sh', '-c']
        args:
          [
            'mkdir -p /mnt/build && tar xzf /mnt/build-artifacts.tar.gz -C /mnt/build && cd /mnt/build && node dist/src/index.js import commoncrawl -d latest',
          ]
      outputs:
        artifacts:
          - name: db
            path: /mnt/build/db.sqlite
