apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
    name: scan-cc
    namespace: argo
spec:
    entrypoint: main
    templates:
        - name: main
          steps:
              - - name: clone-and-build
                  template: clone-and-build-template
              - - name: generate-file-list
                  template: generate-file-list-template
                  arguments:
                      artifacts:
                          - name: build-artifacts
                            from: "{{steps.clone-and-build.outputs.artifacts.build-artifacts}}"
              - - name: split-batches
                  template: split-batches-template
                  arguments:
                    artifacts:
                      - name: file-list
                        from: "{{steps.generate-file-list.outputs.artifacts.file-list}}"
              - - name: scan-web
                  template: scan-web-template
                  arguments:
                    artifacts:
                      - name: file-list
                        from: "{{steps.generate-file-list.outputs.artifacts.file-list}}"
                      - name: build-artifacts
                        from: "{{steps.clone-and-build.outputs.artifacts.build-artifacts}}"
                    parameters:
                      - name: batch-definition
                        value: "{{item}}"
                  withParam: "{{steps.split-batches.outputs.result}}"

        - name: clone-and-build-template
          container:
              image: node:latest
              command: ["/bin/sh", "-c"]
              args: [
                  "git clone --depth 1 https://github.com/kamiljano/scan-web.git && cd scan-web && yarn install && yarn build && tar czf /tmp/build-artifacts.tar.gz ."
              ]
          outputs:
              artifacts:
                  - name: build-artifacts
                    path: /tmp/build-artifacts.tar.gz

        - name: generate-file-list-template
          inputs:
              artifacts:
                  - name: build-artifacts
                    path: /mnt/build-artifacts.tar.gz
          container:
              image: node:latest
              command: ["/bin/sh", "-c"]
              args: [
                  "mkdir -p /mnt/build && tar xzf /mnt/build-artifacts.tar.gz -C /mnt/build && cd /mnt/build && node dist/src/index.js import commoncrawl -d latest --only-list --split-list-every 10000 > batches.json"
              ]
          outputs:
              artifacts:
                  -   name: file-list
                      path: /mnt/build/batches.json

        - name: split-batches-template
          inputs:
            artifacts:
              - name: file-list
                path: /mnt/batches.json
          script:
            image: python:3.9
            command: [ python ]
            source: |
              import json
              import os
              import sys

              with open("/mnt/batches.json", "r") as f:
                  batches = json.load(f)

              batch_names = []
              for idx, batch in enumerate(batches):
                  batch_names.append({"name": f"batch-{idx}", "batchId": idx})

              json.dump(batch_names, sys.stdout)

        - name: scan-web-template
          inputs:
            parameters:
              - name: batch-definition
            artifacts:
              - name: file-list
                path: /mnt/batches.json
              - name: build-artifacts
                path: /tmp/build-artifacts.tar.gz
          container:
            image: node:latest
            command: [sh, -c]
            args: ["echo {{inputs.parameters.batch-definition}} && cat /mnt/batches.json"]
